// ─── WEALTHQUEST FINANCIAL GLOSSARY ──────────────────────────────────────────
// ~170 terms across 10 subject areas. Definitions sourced from CFA Institute,
// Federal Reserve educational materials, SEC investor publications, and
// Investopedia's editorial standards.

export const GLOSSARY_TERMS = [

  // ── UNIT 1: FINANCIAL FOUNDATIONS ────────────────────────────────────────
  { id: "asset",              term: "Asset",                  category: "Foundations", definition: "Anything of economic value owned by a person or entity that can produce income or be converted to cash. Assets appear on the left side of a balance sheet.", example: "Cash, a house, stocks, a patent — all are assets.", context: "Net worth = total assets − total liabilities. Building assets is the core goal of personal finance." },
  { id: "liability",          term: "Liability",              category: "Foundations", definition: "A financial obligation or debt owed to another party. Liabilities appear on the right side of a balance sheet and must be repaid.", example: "A mortgage, credit card balance, and student loan are all liabilities.", context: "High liabilities relative to assets signal financial risk. Reducing liabilities increases net worth." },
  { id: "net-worth",          term: "Net Worth",              category: "Foundations", definition: "The total value of everything you own minus everything you owe. The single most important measure of personal financial health.", example: "Assets of $500K − liabilities of $200K = net worth of $300K.", context: "Tracking net worth annually reveals whether you're genuinely building wealth, regardless of income level." },
  { id: "income",             term: "Income",                 category: "Foundations", definition: "Money received regularly from work, investments, or other sources. Includes earned income (wages) and passive income (dividends, rent).", example: "A $80,000 salary plus $5,000 in stock dividends = $85,000 total annual income.", context: "Income is not wealth — high income with high spending leaves no net worth. What you keep matters more than what you earn." },
  { id: "investment",         term: "Investment",             category: "Foundations", definition: "Allocating money today with the expectation of receiving more money in the future, either through income or price appreciation.", example: "Buying $10,000 of S&P 500 index funds expecting long-term growth is an investment.", context: "The difference between saving and investing: savings preserve capital (low risk); investing grows capital (higher risk, higher return)." },
  { id: "compound-interest",  term: "Compound Interest",      category: "Foundations", definition: "Interest calculated on both the initial principal and all previously accumulated interest. Creates exponential growth over time — the most powerful force in finance.", example: "$10,000 at 10% compounded annually grows to $174,494 in 30 years. Simple interest yields only $40,000.", context: "Einstein reportedly called compound interest the eighth wonder of the world. Time is the most critical variable — starting 10 years earlier can double your final wealth." },
  { id: "simple-interest",    term: "Simple Interest",        category: "Foundations", definition: "Interest calculated only on the original principal amount, not on accumulated interest. Linear rather than exponential growth.", example: "$1,000 at 5% simple interest earns $50 every year — always $50, never growing.", context: "Most savings accounts and short-term loans use simple interest. Compound interest is far more powerful over long periods." },
  { id: "return",             term: "Return",                 category: "Foundations", definition: "The profit or loss on an investment over a period, expressed as a percentage of the amount invested. Includes both price changes and income received.", example: "Buy at $100, sell at $115, receive $3 dividend — total return = 18%.", context: "Always compare returns to a benchmark. A 10% return sounds great until you learn a simple index fund returned 15%." },
  { id: "risk",               term: "Risk",                   category: "Foundations", definition: "The probability and magnitude of financial loss. In investing, risk and return are fundamentally linked — higher expected return requires accepting higher risk.", example: "A government bond has low risk (near-certain repayment); a startup stock has high risk (total loss possible).", context: "Risk is often confused with volatility. True investment risk = permanent loss of capital. Short-term price swings are not risk for long-term investors." },
  { id: "liquidity",          term: "Liquidity",              category: "Foundations", definition: "The ease and speed with which an asset can be converted to cash at or near its fair market value without significantly moving its price.", example: "Apple stock is highly liquid (millions of shares trade daily at tight spreads). A rural farmhouse is illiquid.", context: "Liquidity evaporates in crises — assets that seem liquid in calm markets become hard to sell in panics. Always hold a liquidity buffer." },
  { id: "portfolio",          term: "Portfolio",              category: "Foundations", definition: "The complete collection of all financial investments held by a person or institution — stocks, bonds, cash, real estate, and any other assets.", example: "A balanced portfolio: 50% global stocks, 30% bonds, 10% real estate, 10% cash.", context: "Portfolio construction — how you combine assets — explains 90%+ of long-term investment returns according to academic research." },
  { id: "opportunity-cost",   term: "Opportunity Cost",       category: "Foundations", definition: "The value of the best alternative you give up when making a choice. Every financial decision has a hidden opportunity cost.", example: "Keeping $50,000 in a 0.5% savings account when bonds yield 5% costs $2,250/year in forgone interest.", context: "Opportunity cost is why holding cash long-term destroys wealth — you give up the returns you could have earned in productive assets." },
  { id: "time-value-of-money",term: "Time Value of Money",    category: "Foundations", definition: "The principle that a dollar today is worth more than a dollar in the future, because today's dollar can be invested to earn returns.", example: "$1,000 today at 8% annual return = $1,469 in 5 years. The $469 difference is the time value.", context: "This principle underlies all of finance — stock valuation, bond pricing, mortgage payments, and retirement planning all rest on it." },
  { id: "purchasing-power",   term: "Purchasing Power",       category: "Foundations", definition: "The quantity of goods and services that a unit of money can buy. Inflation erodes purchasing power over time.", example: "What $100 bought in 1990 requires ~$230 today due to 30+ years of inflation.", context: "Preserving purchasing power is why you must invest, not just save. Cash under a mattress loses real value every year." },
  { id: "rule-of-72",         term: "Rule of 72",             category: "Foundations", definition: "A quick mental formula: divide 72 by the annual interest rate to estimate how many years it takes to double money.", example: "At 8% annual return, money doubles in 72÷8 = 9 years. At 6%, it takes 12 years.", context: "The Rule of 72 makes the power of compound interest intuitive. It also works for debt — a 24% credit card doubles what you owe in 3 years." },

  // ── UNIT 2: BANKING & CREDIT ──────────────────────────────────────────────
  { id: "credit-score",       term: "Credit Score",           category: "Banking", definition: "A numerical rating (300–850 in the US FICO system) that measures a borrower's creditworthiness based on payment history, amounts owed, credit history length, new credit, and credit mix.", example: "A 750 credit score typically qualifies for the best mortgage rates. A 580 score may mean loan rejection.", context: "Payment history (35%) is the biggest factor. A single missed payment can drop your score 100 points. Good credit saves tens of thousands over a lifetime in lower interest rates." },
  { id: "apr",                term: "APR (Annual Percentage Rate)", category: "Banking", definition: "The yearly cost of borrowing money, expressed as a percentage, including interest and fees. The true cost of a loan beyond just the interest rate.", example: "A mortgage with a 6.5% interest rate and $3,000 in fees may have a 6.8% APR over 30 years.", context: "Always compare APR, not just the interest rate. Credit cards typically carry 20–30% APR — among the most expensive debt you can carry." },
  { id: "mortgage",           term: "Mortgage",               category: "Banking", definition: "A loan secured by real estate where the property serves as collateral. Typically 15–30 year term with fixed or variable interest rates.", example: "A $400,000 home with 20% down requires a $320,000 mortgage. At 7% for 30 years, monthly payment = $2,129.", context: "A mortgage is likely the largest debt you'll ever carry. On a 30-year mortgage, you pay nearly double the purchase price in total — interest adds up dramatically." },
  { id: "amortization",       term: "Amortization",           category: "Banking", definition: "The process of paying off a loan through regular scheduled payments that cover both principal and interest. Early payments are mostly interest; later payments are mostly principal.", example: "On a $300,000 mortgage at 6%, the first payment might be $1,650 interest and $150 principal. By year 25, it flips.", context: "Understanding amortization reveals why making extra principal payments early saves enormous amounts of interest over the loan's life." },
  { id: "collateral",         term: "Collateral",             category: "Banking", definition: "An asset pledged as security for a loan. If the borrower defaults, the lender can seize and sell the collateral to recover the debt.", example: "Your home is collateral on a mortgage. Your car is collateral on an auto loan.", context: "Secured loans (with collateral) carry lower interest rates than unsecured loans because the lender has a safety net. Never pledge collateral you can't afford to lose." },
  { id: "default",            term: "Default",                category: "Banking", definition: "Failure to repay a debt according to the agreed terms. Can trigger penalties, credit score damage, asset seizure, and legal action.", example: "Missing three consecutive mortgage payments typically triggers the default process and potential foreclosure.", context: "Default has severe, long-lasting consequences. A home foreclosure stays on your credit report for 7 years. Always contact lenders before defaulting — most have hardship programs." },
  { id: "interest-rate",      term: "Interest Rate",          category: "Banking", definition: "The cost of borrowing money, expressed as a percentage of the principal per year. Set by central banks at the short end; determined by markets at longer maturities.", example: "A $300,000 mortgage at 7% annual interest costs $21,000 per year in interest.", context: "Interest rates are the most powerful macro variable in finance — they affect the value of virtually every asset class, from bonds to stocks to real estate." },
  { id: "debt",               term: "Debt",                   category: "Banking", definition: "Money owed by one party to another, with an obligation to repay principal plus agreed interest. Not all debt is bad — it depends on cost, purpose, and capacity to repay.", example: "A $50,000 student loan at 5% for education may create value. $50,000 in credit card debt at 25% destroys it.", context: "Leverage amplifies both gains and losses. Good debt (low cost, productive use) builds wealth. Bad debt (high cost, consumption) destroys it." },
  { id: "emergency-fund",     term: "Emergency Fund",         category: "Banking", definition: "A reserve of 3–6 months of living expenses held in liquid, low-risk accounts specifically for unexpected financial shocks.", example: "Monthly expenses of $3,500 × 6 months = a $21,000 emergency fund target in a high-yield savings account.", context: "Without an emergency fund, any unexpected expense forces you into high-interest debt. The fund is the foundation of financial stability — build it before investing." },
  { id: "budget",             term: "Budget",                 category: "Banking", definition: "A plan allocating expected income across categories of spending and saving over a time period. The fundamental tool of personal financial control.", example: "The 50/30/20 rule: 50% needs, 30% wants, 20% savings/debt repayment.", context: "A budget is not a restriction — it's a plan for spending intentionally. People who budget consistently accumulate significantly more wealth than those who don't." },

  // ── UNIT 3: STOCK MARKET ─────────────────────────────────────────────────
  { id: "equity",             term: "Equity",                 category: "Stocks", definition: "Ownership interest in a company represented by shares. Equity holders have a residual claim on assets after all debts are paid.", example: "Owning 1,000 of Apple's 15.4 billion shares makes you a fractional owner of the entire business.", context: "Equities are the highest-returning asset class historically (~10%/year in the US) but with the most short-term volatility. Time horizon is the key variable." },
  { id: "stock-exchange",     term: "Stock Exchange",         category: "Stocks", definition: "An organized marketplace where buyers and sellers trade shares of publicly listed companies. Major exchanges include NYSE, NASDAQ, London Stock Exchange, and Tokyo Stock Exchange.", example: "When you buy Apple shares on NASDAQ, you're buying from another investor via the exchange's matching system.", context: "Exchanges provide liquidity, price discovery, and regulatory oversight. The NYSE and NASDAQ together account for nearly 40% of global stock trading volume." },
  { id: "ipo",                term: "IPO (Initial Public Offering)", category: "Stocks", definition: "The first sale of a company's shares to the public on a stock exchange. Allows a private company to raise capital from public investors.", example: "When Airbnb went public in December 2020, its IPO raised $3.5B and valued the company at $47B.", context: "Most IPOs underperform the market over 3–5 years. The 'IPO pop' benefits institutional investors who get allocations, not retail investors who buy in the open market." },
  { id: "market-cap",         term: "Market Capitalization",  category: "Stocks", definition: "The total market value of a company's outstanding shares. Calculated as current share price × total shares outstanding.", example: "Apple at $185/share × 15.4B shares = $2.85 trillion market cap — the world's largest.", context: "Categories: Mega (>$200B), Large (>$10B), Mid ($2–10B), Small ($300M–2B), Micro (<$300M). Smaller companies historically outperform but with higher volatility." },
  { id: "earnings-per-share", term: "Earnings Per Share (EPS)", category: "Stocks", definition: "A company's net profit divided by the number of outstanding shares. The most widely used measure of corporate profitability on a per-share basis.", example: "A company with $1B net profit and 500M shares has EPS of $2.00.", context: "EPS growth is the primary driver of long-term stock price appreciation. Earnings that consistently grow 10–15%/year produce outstanding long-term stock returns." },
  { id: "pe-ratio",           term: "Price-to-Earnings Ratio (P/E)", category: "Stocks", definition: "A stock's price divided by its earnings per share. Measures how much investors pay per dollar of earnings. The most widely used valuation metric.", example: "A stock at $50 with $2.50 EPS has a P/E of 20× — investors pay $20 for each $1 of annual earnings.", context: "The S&P 500 historically trades at 15–20× earnings. Above 25× suggests expensive; below 12× suggests cheap (but may signal problems). Always compare P/E to sector peers and history." },
  { id: "dividends",          term: "Dividends",              category: "Stocks", definition: "Cash distributions paid by a company to shareholders from profits, typically quarterly. Represent a direct share of company earnings.", example: "Johnson & Johnson pays $1.19/share quarterly — about 3% annual dividend yield on a $159 stock.", context: "Reinvesting dividends (DRIP) dramatically accelerates compounding. Historically, dividends have accounted for ~40% of total stock market returns." },
  { id: "capital-gain",       term: "Capital Gain",           category: "Stocks", definition: "Profit from selling an investment for more than its purchase price. Short-term gains (held <1 year) taxed as ordinary income; long-term gains at preferential 0–20% rates.", example: "Buy at $50, sell at $80 — the $30/share is a capital gain.", context: "Tax-efficient investing means holding investments >1 year to qualify for lower long-term capital gains rates. The difference can be 20%+ vs 37% for high earners." },
  { id: "capital-loss",       term: "Capital Loss",           category: "Stocks", definition: "A loss from selling an investment below its purchase price. Can offset capital gains and up to $3,000 of ordinary income annually.", example: "Bought at $100, sold at $70 — $30 capital loss that reduces your tax bill.", context: "Tax-loss harvesting: strategically selling losers to offset winners. A disciplined tax-loss harvesting strategy can add 0.5–1.5% to after-tax returns annually." },
  { id: "short-selling",      term: "Short Selling",          category: "Stocks", definition: "Borrowing shares and selling them, hoping to buy them back cheaper later. Profits if price falls; losses if price rises — potentially unlimited.", example: "Short 100 shares at $80, buy back at $50 → $3,000 profit. If stock rises to $120, you lose $4,000.", context: "Short sellers serve an important market function by identifying overvalued companies. But losses are theoretically unlimited — price can keep rising. High risk." },
  { id: "market-order",       term: "Market Order",           category: "Stocks", definition: "An order to buy or sell a security immediately at the best available current price, prioritizing execution speed over price precision.", example: "Place a market order to buy 100 Apple shares — it fills within seconds at whatever the ask price is.", context: "Market orders guarantee execution but not price. In volatile or illiquid markets, you may receive a significantly different price than expected (slippage)." },
  { id: "limit-order",        term: "Limit Order",            category: "Stocks", definition: "An order to buy or sell a security only at a specified price or better. Guarantees price but not execution — may not fill if the market never reaches your price.", example: "Set a limit buy at $140 for a $145 stock. The order only fills if price drops to $140 or below.", context: "Limit orders protect against bad fills but risk missing the trade entirely. Used by professional traders who prioritize price over certainty of execution." },
  { id: "volume",             term: "Trading Volume",         category: "Stocks", definition: "The total number of shares traded during a given period. High volume confirms price moves; low volume on price moves signals weak conviction.", example: "Apple's average daily volume is ~55 million shares. A day with 200M shares traded signals major news or institutional activity.", context: "Volume is the market's fuel. Breakouts on high volume are more reliable than breakouts on low volume. Volume precedes price — watch it carefully." },
  { id: "bid-ask-spread",     term: "Bid-Ask Spread",         category: "Stocks", definition: "The difference between the highest price a buyer will pay (bid) and the lowest price a seller will accept (ask). Represents the immediate cost of trading.", example: "If the bid is $99.95 and ask is $100.05, the spread is $0.10. Buy at $100.05, immediately sell at $99.95 = instant $0.10 loss.", context: "For liquid large-caps, spreads are fractions of a cent. For illiquid small-caps or ETFs, spreads can be 1–5% — a huge hidden cost for active traders." },
  { id: "benchmark",          term: "Benchmark",              category: "Stocks", definition: "A standard index used to evaluate investment performance. The most common benchmark for US equities is the S&P 500.", example: "If your fund returned 8% while the S&P 500 returned 12%, you underperformed your benchmark by 4%.", context: "Most active fund managers fail to beat their benchmark after fees over 10+ years. This is the core argument for passive index investing." },

  // ── UNIT 4: FUNDS & PASSIVE INVESTING ────────────────────────────────────
  { id: "etf",                term: "ETF (Exchange-Traded Fund)", category: "Funds", definition: "A fund tracking an index, sector, or theme that trades on stock exchanges like a regular stock throughout the day at real-time prices.", example: "SPY tracks the S&P 500 — buy one share and you own a slice of 500 companies for a 0.09% annual fee.", context: "ETFs revolutionized investing by combining index diversification with low costs and intraday liquidity. Over $10T is now in passive ETFs globally." },
  { id: "mutual-fund",        term: "Mutual Fund",             category: "Funds", definition: "A pooled investment vehicle that collects money from many investors and invests it in a diversified portfolio, priced once per day at NAV.", example: "Vanguard Total Stock Market Mutual Fund pools billions from millions of investors into one diversified US stock portfolio.", context: "Mutual funds were the original democratizing investment vehicle. ETFs have largely replaced them for new money due to lower costs and better tax efficiency." },
  { id: "index-fund",         term: "Index Fund",              category: "Funds", definition: "A fund that passively replicates a market index (like the S&P 500), buying all or most of the same securities in the same proportions. Extremely low cost.", example: "A S&P 500 index fund owns all 500 companies proportionally. When Apple's weight rises, the fund's Apple position rises automatically.", context: "Index funds beat 85–92% of actively managed funds over 15+ years after fees. Jack Bogle's creation of the first index fund at Vanguard in 1976 changed investing forever." },
  { id: "expense-ratio",      term: "Expense Ratio",           category: "Funds", definition: "The annual fee a fund charges expressed as a percentage of assets under management. Directly reduces investor returns.", example: "A 1% expense ratio on $100,000 costs $1,000/year. A 0.03% ratio on the same amount costs $30.", context: "The difference between a 1% and 0.05% expense ratio compounds dramatically — over 30 years on $100,000, it could mean $200,000+ less wealth. Costs are the only guaranteed return." },
  { id: "nav",                term: "NAV (Net Asset Value)",   category: "Funds", definition: "The per-share value of a fund, calculated as total assets minus total liabilities divided by shares outstanding. Mutual funds price once daily at NAV.", example: "A fund with $100M assets, $2M liabilities, and 10M shares has NAV = $9.80/share.", context: "ETFs trade continuously on exchanges, often at slight premiums/discounts to NAV. Mutual funds always transact at end-of-day NAV regardless of when you place your order." },
  { id: "diversification",    term: "Diversification",         category: "Funds", definition: "Spreading investments across different assets, sectors, geographies, and asset classes to reduce portfolio risk without necessarily reducing expected returns.", example: "Instead of owning one stock that could go to zero, an S&P 500 ETF spreads risk across 500 companies.", context: "Nobel laureate Harry Markowitz proved diversification is the 'only free lunch in investing' — it reduces risk without sacrificing expected returns. Correlation is the key variable." },
  { id: "asset-allocation",   term: "Asset Allocation",        category: "Funds", definition: "The strategic distribution of investments across different asset classes based on an investor's risk tolerance, time horizon, and goals.", example: "Classic 60/40: 60% stocks for growth, 40% bonds for stability. More aggressive: 90/10 stocks/bonds.", context: "Asset allocation explains ~90% of portfolio return variation over time, according to landmark research by Brinson, Hood, and Beebower (1986). It's the most important investment decision." },
  { id: "401k",               term: "401(k)",                  category: "Funds", definition: "An employer-sponsored US retirement savings plan allowing pre-tax contributions that grow tax-deferred. Employer matching is effectively free money.", example: "Contribute $23,000/year (2024 limit). At $80K salary with 50% match up to 6%, employer adds $2,400 free.", context: "Always contribute at least enough to get the full employer match — it's an instant 50–100% return on that money. The 401(k) is the most powerful wealth-building tool available to most Americans." },
  { id: "ira",                term: "IRA (Individual Retirement Account)", category: "Funds", definition: "A personal US retirement savings account with tax advantages. Traditional IRA: tax-deductible contributions, taxable withdrawals. Roth IRA: after-tax contributions, tax-free growth and withdrawals.", example: "At $7,000/year contributed to a Roth IRA from age 22, invested at 8%, you'll have ~$2.5M tax-free at 65.", context: "The Roth IRA is one of the most powerful wealth-building tools in the US tax code — decades of compound growth with zero tax on withdrawal." },
  { id: "tax-loss-harvesting",term: "Tax-Loss Harvesting",     category: "Funds", definition: "Deliberately selling investments at a loss to offset capital gains taxes, then immediately replacing with similar (not identical) investments to maintain market exposure.", example: "Sell S&P 500 ETF down 15% to harvest the loss, immediately buy a different S&P 500 ETF. Tax savings without changing your investment position.", context: "A consistent tax-loss harvesting strategy adds an estimated 0.5–1.5% to annual after-tax returns — with no change in risk or expected pre-tax return." },

  // ── UNIT 5: FIXED INCOME ─────────────────────────────────────────────────
  { id: "bonds",              term: "Bonds",                   category: "Fixed Income", definition: "Debt instruments issued by governments or corporations. Investors lend money and receive periodic interest (coupon) plus return of principal at maturity.", example: "A 10-year US Treasury bond at 4.5% pays $45/year per $1,000 face value and returns $1,000 in 10 years.", context: "The global bond market (~$130T) is larger than the stock market. Bonds are the foundation of institutional investing and a key tool for income and stability." },
  { id: "coupon",             term: "Coupon",                  category: "Fixed Income", definition: "The fixed annual interest payment made by a bond issuer to the bondholder, expressed as a percentage of face value.", example: "A $1,000 bond with a 5% coupon pays $50/year (typically $25 every six months).", context: "Named after physical coupons investors once clipped from paper bonds. All payments are now electronic. The coupon rate is set at issuance and never changes." },
  { id: "yield",              term: "Yield",                   category: "Fixed Income", definition: "The income return on a bond, expressed as a percentage of its current market price. Yield and price move inversely — when prices fall, yields rise.", example: "A bond paying $50 annually trading at $900 has a current yield of 5.56% ($50 ÷ $900).", context: "Yield is what you actually earn if you buy today — more useful than the coupon rate for making investment decisions." },
  { id: "duration",           term: "Duration",                category: "Fixed Income", definition: "A bond's price sensitivity to interest rate changes. A bond with 8-year duration loses ~8% of value if rates rise 1%, and gains ~8% if rates fall 1%.", example: "Long-term Treasury bonds (20+ year duration) lost 40%+ when rates rose sharply in 2022.", context: "Duration is the key risk management tool for fixed income. Short-duration bonds are safer in rising-rate environments. Long-duration bonds amplify interest rate bets." },
  { id: "face-value",         term: "Face Value (Par Value)",  category: "Fixed Income", definition: "The nominal value of a bond — what the issuer promises to repay at maturity. Most bonds have $1,000 face value. Bonds trade at premiums (>par) or discounts (<par).", example: "Buy a bond at $950 discount; receive $1,000 at maturity — earning $50 capital gain plus the coupon.", context: "New bonds are issued at or near face value. As interest rates change, existing bonds trade away from face value in the secondary market." },
  { id: "yield-curve",        term: "Yield Curve",             category: "Fixed Income", definition: "A chart showing interest rates across bond maturities (3 months to 30 years). Normally slopes upward. An inverted curve (short > long rates) signals recession.", example: "In 2022–2023, the yield curve inverted as 6-month Treasury yields exceeded 30-year yields, predicting the economic slowdown.", context: "The yield curve has inverted before every US recession since the 1950s. It's the most reliable macroeconomic leading indicator available." },
  { id: "government-bonds",   term: "Government Bonds",        category: "Fixed Income", definition: "Debt issued by national governments. Considered the safest bonds since governments can tax citizens and (in some cases) print currency to meet obligations.", example: "US Treasuries, UK Gilts, German Bunds. The 10-year US Treasury yield is the global 'risk-free rate' benchmark.", context: "In crises, investors flood into government bonds ('flight to quality'), driving yields down. They are the bedrock of safe portfolio construction worldwide." },
  { id: "corporate-bond",     term: "Corporate Bond",          category: "Fixed Income", definition: "Debt issued by a company to raise capital. Yield is higher than government bonds to compensate for credit risk — the risk the company defaults.", example: "Investment-grade Apple bonds yield ~5%. A junk-rated company might yield 9–10% for the same maturity.", context: "Investment-grade corporate bonds (BBB− and above) have historically had low default rates. High-yield bonds can see 10%+ default rates in recessions." },
  { id: "high-yield-bond",    term: "High-Yield Bond",         category: "Fixed Income", definition: "Bonds rated below investment grade (BB+ or lower by S&P/Fitch) that pay higher yields to compensate for elevated default risk. Also called 'junk bonds.'", example: "A startup with uncertain cash flows issues bonds at 10% yield — investors demand this premium for the high bankruptcy risk.", context: "High-yield bonds are strongly correlated with equities during downturns. In recessions, default rates can reach 10–15%. Essential to diversify across many issuers." },
  { id: "credit-rating",      term: "Credit Rating",           category: "Fixed Income", definition: "A letter-grade assessment of a bond issuer's ability to repay debt, issued by agencies such as Moody's, S&P, and Fitch. Investment grade: BBB−/Baa3 and above.", example: "AAA: Apple, Microsoft. BB: many energy companies. CCC: distressed retailers near default.", context: "Credit ratings directly affect borrowing costs. A downgrade from investment grade to junk forces many institutional funds to sell — often causing sharp price drops." },

  // ── UNIT 6: MACROECONOMICS ────────────────────────────────────────────────
  { id: "gdp",                term: "GDP (Gross Domestic Product)", category: "Macro", definition: "The total market value of all finished goods and services produced within a country in a specific period. The primary measure of economic size and health.", example: "US GDP is ~$27 trillion. A 2% real growth rate = $540B more economic output than the prior year.", context: "Two consecutive quarters of negative GDP = recession. GDP growth drives corporate earnings, employment, and ultimately stock market returns." },
  { id: "inflation",          term: "Inflation",               category: "Macro", definition: "The rate at which the general price level of goods and services rises, reducing purchasing power. Measured by CPI, PCE, and PPI in the US.", example: "At 3% annual inflation, $100 today buys only $74 of goods in 10 years.", context: "The Federal Reserve targets 2% inflation as the 'Goldilocks' level. Too little risks deflation; too much erodes savings and triggers rate hikes that hurt stocks and bonds." },
  { id: "unemployment-rate",  term: "Unemployment Rate",       category: "Macro", definition: "The percentage of the labor force actively seeking but unable to find work. A key gauge of economic health. Full employment is typically ~4–5% in the US.", example: "COVID-19 sent US unemployment from 3.5% to 14.7% in April 2020 — the fastest spike in modern history.", context: "Unemployment lags the economic cycle — it peaks after recessions officially end. The Fed monitors it closely alongside inflation in its dual mandate." },
  { id: "cpi",                term: "CPI (Consumer Price Index)", category: "Macro", definition: "A measure of the average change over time in prices paid by urban consumers for a basket of goods and services. The most widely cited inflation gauge.", example: "If the CPI basket cost $100 last year and $103 this year, CPI inflation is 3%.", context: "Monthly CPI releases are among the most market-moving events on the economic calendar. Core CPI (excluding food and energy) is the Fed's preferred near-term inflation gauge." },
  { id: "federal-reserve",    term: "Federal Reserve (The Fed)", category: "Macro", definition: "The central bank of the United States, responsible for monetary policy, bank regulation, and financial stability. Sets the federal funds rate — the benchmark for all US interest rates.", example: "In 2022–2023, the Fed raised rates 11 times, from 0.25% to 5.5% — the fastest hiking cycle in 40 years.", context: "Markets obsessively parse Fed communications. 'Don't fight the Fed' is one of the oldest rules in investing — monetary policy overwhelms most other factors in the short term." },
  { id: "monetary-policy",    term: "Monetary Policy",         category: "Macro", definition: "Central bank actions controlling money supply and interest rates to achieve price stability and maximum employment. Expansionary = lower rates; Contractionary = higher rates.", example: "The Fed cutting rates to 0% during COVID-19 was extremely expansionary — boosting asset prices and economic activity.", context: "Monetary policy is the Fed's primary lever. It affects every asset class: lower rates boost stocks and bonds; higher rates suppress them. All investors must understand it." },
  { id: "fiscal-policy",      term: "Fiscal Policy",           category: "Macro", definition: "Government decisions on spending and taxation to influence the economy. Expansionary = more spending or tax cuts; Contractionary = spending cuts or tax increases.", example: "The $2.2T CARES Act (2020) was expansionary fiscal policy — government spending to support the economy during COVID.", context: "Fiscal policy is controlled by Congress; monetary policy by the Fed. In crises, both are deployed simultaneously. Excessive fiscal stimulus risks inflation." },
  { id: "recession",          term: "Recession",               category: "Macro", definition: "A significant, widespread, prolonged decline in economic activity. Technically defined as two consecutive quarters of negative real GDP growth.", example: "The US entered recession in Q1–Q2 2020 due to COVID-19. GDP fell 31.4% annualized in Q2 2020.", context: "Markets typically bottom 6–9 months before recessions officially end — recovery begins while economists are still reporting terrible data. The best buying opportunities occur in recessions." },
  { id: "stagflation",        term: "Stagflation",             category: "Macro", definition: "The simultaneous combination of high inflation, slow economic growth, and high unemployment. Extremely difficult for central banks to address without worsening one or more components.", example: "The 1970s US stagflation: oil shocks caused 10%+ inflation while unemployment hit 9% and growth stalled.", context: "Stagflation is the worst macroeconomic environment for investors — bonds fall (inflation), stocks struggle (slow growth), and cash loses value. Commodities and real assets tend to outperform." },
  { id: "quantitative-easing",term: "Quantitative Easing (QE)", category: "Macro", definition: "A central bank policy of buying government securities and other assets to inject money into the economy, reduce long-term interest rates, and stimulate activity.", example: "The Federal Reserve's balance sheet expanded from $900B to $9T between 2008 and 2022 via QE programs.", context: "QE inflates asset prices (good for investors) but risks inflation and asset bubbles if maintained too long. The reversal (QT — quantitative tightening) drains liquidity and pressures markets." },

  // ── UNIT 7: RISK & PORTFOLIO THEORY ──────────────────────────────────────
  { id: "volatility",         term: "Volatility",              category: "Risk", definition: "The degree of price variation of an asset over time. Measured statistically as standard deviation of returns. High volatility = large, rapid price swings.", example: "The S&P 500 has ~15% annual volatility. Bitcoin has ~70–80% annual volatility.", context: "Volatility is the price of returns. Higher long-run returns require tolerating higher short-term volatility. An investor's ability to tolerate volatility defines their optimal asset allocation." },
  { id: "beta",               term: "Beta",                    category: "Risk", definition: "A measure of an investment's volatility relative to the market. Beta of 1 = moves with market; >1 = more volatile; <1 = less volatile; negative = moves opposite market.", example: "A stock with beta 1.5 typically rises 15% when the market rises 10%, and falls 15% when the market falls 10%.", context: "High-beta stocks amplify bull market gains but amplify bear market losses. Low-beta stocks (utilities, consumer staples) preserve capital better in downturns." },
  { id: "correlation",        term: "Correlation",             category: "Risk", definition: "A statistical measure (−1 to +1) of how two investments move relative to each other. +1 = move in perfect lockstep; −1 = move in perfect opposition; 0 = no relationship.", example: "US stocks and US government bonds often have −0.2 to −0.5 correlation — when stocks fall sharply, bonds often rise.", context: "The lower the correlation between assets, the greater the diversification benefit. This is the mathematical foundation of Modern Portfolio Theory." },
  { id: "drawdown",           term: "Drawdown",                category: "Risk", definition: "The peak-to-trough decline of an investment before a new peak is reached. Maximum drawdown is the worst historical peak-to-trough loss.", example: "A portfolio goes from $100K to $60K — a 40% drawdown. It needs a 67% gain just to recover.", context: "The asymmetry of losses is brutal: a 50% loss requires a 100% gain to recover. Limiting drawdown is as important as maximizing returns for long-term wealth building." },
  { id: "sharpe-ratio",       term: "Sharpe Ratio",            category: "Risk", definition: "Risk-adjusted return metric = (portfolio return − risk-free rate) ÷ standard deviation. Measures how much return you earn per unit of risk taken.", example: "Portfolio returns 12% with 10% volatility; risk-free rate 4%. Sharpe = (12−4)/10 = 0.8. Industry standard: >1 is good, >2 is excellent.", context: "Sharpe ratio lets you compare any two investments fairly regardless of risk level. A lower-return portfolio with a higher Sharpe is actually a better investment per unit of risk." },
  { id: "alpha",              term: "Alpha",                   category: "Risk", definition: "The excess return of an investment versus its benchmark, after accounting for risk (beta). Positive alpha = outperformance from skill; negative = underperformance.", example: "Fund returns 14% when the market returns 12% with same beta of 1 — alpha = +2%. Manager added value.", context: "Most professional fund managers produce negative alpha after fees. Consistent, statistically significant alpha is extremely rare and highly valuable." },
  { id: "leverage",           term: "Leverage",                category: "Risk", definition: "Using borrowed money to amplify investment exposure. A 2× leveraged position doubles both gains and losses relative to the underlying asset.", example: "$10K own money + $10K borrowed = $20K invested (2× leverage). A 20% gain = 40% return. A 20% loss = 40% loss — plus interest.", context: "Leverage destroys portfolios when combined with volatility. LTCM (1998) and Archegos (2021) both had 5–10× leverage. Excessive leverage is the most common cause of catastrophic financial failure." },
  { id: "value-at-risk",      term: "Value at Risk (VaR)",     category: "Risk", definition: "A statistical estimate of the maximum potential loss over a specific time period at a given confidence level.", example: "A portfolio's 1-day 95% VaR of $50,000 means there's a 5% chance of losing more than $50,000 in a single day.", context: "VaR is standard risk management language for banks and institutions. Its weakness: it tells you nothing about losses beyond the confidence level — exactly where catastrophic risks live." },
  { id: "black-swan",         term: "Black Swan",              category: "Risk", definition: "A rare, highly impactful, unpredictable event that falls outside normal expectations and is often rationalized in hindsight as having been predictable.", example: "The 2008 financial crisis, COVID-19 pandemic, and 9/11 were black swan events for financial markets.", context: "Term coined by Nassim Nicholas Taleb. Black swans cause the most extreme market dislocations. Portfolios must be stress-tested for low-probability, high-impact scenarios." },
  { id: "market-risk",        term: "Market Risk (Systematic Risk)", category: "Risk", definition: "The risk of losses from broad market movements that affect all investments and cannot be eliminated through diversification. The non-diversifiable component of total risk.", example: "In the 2008 crash, virtually all equities fell simultaneously — no amount of diversification within equities prevented losses.", context: "Market risk is compensated by the equity risk premium (~5% historically over risk-free rate). It's the price you pay for expected excess returns from owning stocks." },

  // ── UNIT 8: DERIVATIVES & OPTIONS ────────────────────────────────────────
  { id: "derivatives",        term: "Derivatives",             category: "Derivatives", definition: "Financial instruments whose value is derived from an underlying asset — stocks, bonds, commodities, currencies, or interest rates. Used for hedging and speculation.", example: "An oil futures contract is a derivative — its value depends entirely on crude oil prices.", context: "The global derivatives market is estimated at $600T–$1 quadrillion notional value. Used by every major institution to manage risk." },
  { id: "options",            term: "Options",                 category: "Derivatives", definition: "Contracts giving the holder the right — but not obligation — to buy (call) or sell (put) an asset at a specified price before a specified date.", example: "Buying a put option on the S&P 500 at the 4,000 strike is like buying insurance on your portfolio — if markets crash, your put profits.", context: "Options buyers have limited loss (the premium paid). Options sellers have unlimited theoretical risk. Used for hedging, income generation, and speculation." },
  { id: "call-option",        term: "Call Option",             category: "Derivatives", definition: "A contract giving the holder the right to buy an underlying asset at the strike price before expiration. Profitable when the asset rises above strike + premium paid.", example: "Buy a $200 call on Apple. If Apple rises to $230, your call is worth $30 (minus premium). If Apple stays below $200, the call expires worthless.", context: "Call options are used to speculate on price increases with limited capital. Maximum loss is the premium paid; maximum gain is theoretically unlimited." },
  { id: "put-option",         term: "Put Option",              category: "Derivatives", definition: "A contract giving the holder the right to sell an underlying asset at the strike price before expiration. Acts as portfolio insurance — profits when the asset falls.", example: "Buy a $100 put on a stock trading at $100. If it falls to $70, your put gains $30 in value (minus premium paid).", context: "Protective puts are like insurance on stock positions. Institutional investors buy puts on indices to hedge portfolio downside during uncertain periods." },
  { id: "strike-price",       term: "Strike Price",            category: "Derivatives", definition: "The predetermined price at which an option holder can buy (call) or sell (put) the underlying asset. Set at the time the option contract is written.", example: "A call option with a $150 strike on a $145 stock is out of the money. At $155, it's in the money by $5.", context: "Strike selection is the key options trading decision. In-the-money options cost more but have higher probability of profit. Out-of-the-money options are cheaper but have lower probability." },
  { id: "implied-volatility",  term: "Implied Volatility",     category: "Derivatives", definition: "The market's forecast of an asset's likely price movement, derived from current option prices. High IV = expensive options; low IV = cheap options. Often called 'fear gauge.'", example: "VIX (S&P 500 implied volatility) typically sits at 15–20 in calm markets, spikes to 40–80+ in crises.", context: "'Buy low IV, sell high IV' is a core options principle. IV tends to spike during fear and collapse after events — a systematic edge for volatility sellers." },
  { id: "futures",            term: "Futures",                 category: "Derivatives", definition: "Contracts obligating the buyer to purchase and the seller to deliver an asset at a predetermined price on a specific future date. Unlike options, both parties must fulfill the contract.", example: "An airline buys crude oil futures at $80/barrel to lock in jet fuel costs 6 months out, regardless of what oil does.", context: "Futures markets provide price discovery and hedging for commodities, currencies, and financial instruments. They're zero-sum — every dollar gained by one party is lost by another." },
  { id: "hedging",            term: "Hedging",                 category: "Derivatives", definition: "Reducing risk by taking an offsetting position in a correlated asset. Hedges reduce both downside risk and upside potential — the cost of protection.", example: "Own $1M in US stocks? Buy S&P 500 put options to hedge against a crash. Costs 1–3% annually but limits catastrophic losses.", context: "Perfect hedging eliminates all risk (and all gain). Practical hedging reduces risk at an acceptable cost. Large institutions hedge continuously; retail investors rarely do." },
  { id: "covered-call",       term: "Covered Call",            category: "Derivatives", definition: "An options strategy where you own the underlying stock and sell call options against it to generate income. Caps your upside but produces regular premium income.", example: "Own 100 Apple shares at $185. Sell a $200 call for $3/share = $300 immediate income. If Apple stays below $200, keep the premium.", context: "Covered calls are the most popular options strategy for income. Widely used by conservative investors and institutions to boost yield on equity holdings." },

  // ── UNIT 9: BEHAVIORAL FINANCE ────────────────────────────────────────────
  { id: "loss-aversion",      term: "Loss Aversion",           category: "Behavioral", definition: "The psychological tendency to feel losses ~2× more intensely than equivalent gains. Causes irrational financial decisions like holding losers too long and selling winners too soon.", example: "Losing $100 feels as bad as gaining $200 feels good. This asymmetry drives poor investment behavior.", context: "Identified by Kahneman and Tversky (Nobel Prize 2002). Loss aversion explains why investors panic-sell at market bottoms — the pain of further loss outweighs rational assessment of expected return." },
  { id: "confirmation-bias",  term: "Confirmation Bias",       category: "Behavioral", definition: "The tendency to search for, interpret, and remember information that confirms existing beliefs while ignoring contradictory evidence.", example: "An investor bullish on a stock seeks out positive news, dismisses negative analyst reports, and over-weights bullish commentary.", context: "Confirmation bias leads to over-concentration in investments you already like. Actively seeking out the best counter-arguments to your thesis is an essential discipline for good investing." },
  { id: "anchoring",          term: "Anchoring Bias",          category: "Behavioral", definition: "The tendency to over-rely on the first piece of information encountered (the 'anchor') when making decisions, even if it's irrelevant.", example: "A stock's 52-week high of $100 anchors investors. When it falls to $60, they think it's 'cheap' versus the anchor — even if $40 is fair value.", context: "Anchoring is why many investors hold losing stocks 'until I get back to even.' The purchase price is irrelevant to future performance — only future prospects matter." },
  { id: "recency-bias",       term: "Recency Bias",            category: "Behavioral", definition: "The tendency to overweight recent events when forming expectations about the future, assuming recent trends will continue indefinitely.", example: "After a 3-year bull market, investors assume stocks always go up. After a crash, they assume markets will keep falling.", context: "Recency bias causes investors to buy high (after recent gains) and sell low (after recent losses) — the exact opposite of rational behavior. Systematic rebalancing counteracts it." },
  { id: "overconfidence",     term: "Overconfidence Bias",     category: "Behavioral", definition: "The tendency for investors to overestimate their ability to predict outcomes, time the market, or pick outperforming stocks.", example: "Studies show 70–80% of individual investors think they're above-average stock pickers. Statistically impossible.", context: "Overconfidence causes excessive trading (which destroys returns via fees and taxes) and under-diversification. Humility about your edge vs. the collective market is the first step to better investing." },
  { id: "herding",            term: "Herding",                 category: "Behavioral", definition: "The tendency of investors to follow and copy what other investors are doing rather than making independent judgments based on their own analysis.", example: "During the dot-com bubble, millions of investors piled into any internet stock — because everyone else was. Most lost everything.", context: "Herding creates bubbles and panics. The crowd is right during trends but catastrophically wrong at turning points. Successful contrarian investing requires going against the herd at critical moments." },
  { id: "sunk-cost-fallacy",  term: "Sunk Cost Fallacy",       category: "Behavioral", definition: "Continuing to hold an investment because of the amount already invested (which cannot be recovered), rather than on the merits of the future investment case.", example: "'I've already lost 40% on this stock — I can't sell now.' But past losses are irrelevant to future performance.", context: "The sunk cost fallacy traps investors in losing positions indefinitely. Ask only: 'Would I buy this today at this price?' If no — sell it. The past is irrelevant." },
  { id: "disposition-effect", term: "Disposition Effect",      category: "Behavioral", definition: "The behavioral tendency to sell winning investments too quickly (to 'lock in' gains) and hold losing investments too long (to avoid realizing losses).", example: "Selling Apple after a 30% gain but holding a down-60% meme stock 'hoping to recover' — the classic disposition pattern.", context: "The disposition effect is the opposite of optimal tax strategy (hold winners, harvest losses). Recognizing this bias allows you to reverse it — hold winners longer, cut losers faster." },
  { id: "dollar-cost-averaging", term: "Dollar-Cost Averaging (DCA)", category: "Behavioral", definition: "Investing a fixed dollar amount at regular intervals regardless of price. Automatically buys more shares when prices are low and fewer when prices are high.", example: "Investing $500/month in an S&P 500 ETF every month for 20 years, regardless of market conditions.", context: "DCA removes the impossible task of market timing. It's psychologically powerful — consistent investing regardless of fear/greed is how most people build substantial wealth." },
  { id: "rebalancing",        term: "Rebalancing",             category: "Behavioral", definition: "Periodically restoring a portfolio to its target asset allocation by selling outperformers and buying underperformers.", example: "60/40 portfolio drifts to 75/25 after a stock rally. Sell stocks, buy bonds to return to 60/40 target.", context: "Rebalancing systematically enforces 'sell high, buy low.' Annual rebalancing has been shown to improve risk-adjusted returns by 0.5–1.0% — while also maintaining your intended risk level." },

  // ── UNIT 10: TECHNICAL & FUNDAMENTAL ANALYSIS ────────────────────────────
  { id: "support",            term: "Support Level",           category: "Technical Analysis", definition: "A price level where buying interest is historically strong enough to prevent further price decline. Acts as a floor that price tends to bounce from.", example: "A stock repeatedly bounced at $50 over 12 months — $50 is a major support level. Traders buy there expecting a bounce.", context: "Support and resistance are self-fulfilling — traders watch these levels, place orders there, and create the very bounces they anticipate. Breaks of major support are significant bearish signals." },
  { id: "resistance",         term: "Resistance Level",        category: "Technical Analysis", definition: "A price level where selling pressure historically prevents further price advances. Acts as a ceiling that price struggles to break through.", example: "A stock repeatedly failed at $100 over 8 months — $100 is major resistance. A break above $100 on high volume is a bullish breakout signal.", context: "When price breaks through resistance on high volume, that level often 'flips' to become new support. This polarity shift is a core technical analysis concept." },
  { id: "moving-average",     term: "Moving Average",          category: "Technical Analysis", definition: "The average price of an asset over a specific number of past periods, updated continuously. Smooths price data to identify trends while filtering short-term noise.", example: "A 200-day moving average of a stock's price — if the stock is above it, the trend is up; below, the trend is down.", context: "The 50-day and 200-day moving averages are the most widely watched technical levels. A 'golden cross' (50-day crosses above 200-day) is a bullish signal; 'death cross' is bearish." },
  { id: "rsi",                term: "RSI (Relative Strength Index)", category: "Technical Analysis", definition: "A momentum oscillator measuring the speed and magnitude of price changes on a 0–100 scale. Above 70 = potentially overbought; below 30 = potentially oversold.", example: "A stock with RSI 82 has rallied sharply and may be extended. Traders watch for a pullback to 50–60 before adding positions.", context: "RSI is one of the most widely used technical indicators. But overbought doesn't mean 'sell' — strong trends can stay overbought for months. RSI divergence (price makes new high, RSI doesn't) is the more reliable signal." },
  { id: "macd",               term: "MACD",                    category: "Technical Analysis", definition: "Moving Average Convergence Divergence — a trend-following momentum indicator showing the relationship between two exponential moving averages (typically 12-day and 26-day).", example: "When the MACD line crosses above the signal line, it's a bullish signal. When it crosses below, it's bearish.", context: "MACD is useful for identifying trend changes and momentum shifts. It lags price action (being based on moving averages), so it's more reliable in trending than ranging markets." },
  { id: "income-statement",   term: "Income Statement",        category: "Fundamental Analysis", definition: "A financial statement showing a company's revenues, expenses, and profits over a period. Answers the question: 'Is this business making money?'", example: "Revenue: $100B. Cost of goods sold: $60B. Gross profit: $40B. Operating expenses: $20B. Net income: $15B (after tax).", context: "The income statement shows profitability but not cash generation. Companies can be profitable but cash-flow negative — always pair the income statement with the cash flow statement." },
  { id: "balance-sheet",      term: "Balance Sheet",           category: "Fundamental Analysis", definition: "A financial snapshot showing a company's assets, liabilities, and shareholders' equity at a single point in time. Equation: Assets = Liabilities + Equity.", example: "Apple's balance sheet: $353B assets, $290B liabilities, $63B shareholders' equity. Net cash position of ~$50B.", context: "A strong balance sheet (low debt, high cash) gives companies resilience through downturns and the ability to invest opportunistically. Balance sheet quality separates survivors from casualties in recessions." },
  { id: "free-cash-flow",     term: "Free Cash Flow (FCF)",    category: "Fundamental Analysis", definition: "Cash generated by a business after capital expenditures — the cash truly available to reward shareholders through dividends, buybacks, or acquisitions.", example: "Company earns $2B net income and spends $500M on equipment (capex). FCF = $1.5B — the real cash the business generates.", context: "Warren Buffett focuses on FCF as the truest measure of business value. 'Earnings are opinion; cash is fact.' FCF-based valuations are more reliable than P/E for capital-intensive businesses." },
  { id: "roe",                term: "Return on Equity (ROE)",  category: "Fundamental Analysis", definition: "Net income divided by shareholders' equity. Measures how efficiently a company generates profit from shareholders' invested capital.", example: "Company earns $1B net income on $5B equity → ROE = 20%. Industry average is 12% → this company is highly efficient.", context: "Warren Buffett looks for companies with consistent ROE above 15%. High ROE businesses generate more value per dollar of capital than low ROE businesses." },
  { id: "debt-to-equity",     term: "Debt-to-Equity Ratio",   category: "Fundamental Analysis", definition: "Total debt divided by shareholders' equity. Measures financial leverage — how much a company relies on debt versus equity to finance its assets.", example: "A D/E ratio of 2.0 means $2 of debt for every $1 of equity. Higher ratio = more leveraged and potentially riskier.", context: "Acceptable D/E varies by industry. Utilities routinely carry 2–3× D/E. Technology companies often have <0.5×. High D/E amplifies returns in good times and losses in bad times." },
  { id: "ev-ebitda",          term: "EV/EBITDA",               category: "Fundamental Analysis", definition: "Enterprise Value divided by EBITDA (Earnings Before Interest, Taxes, Depreciation, and Amortization). A capital-structure-neutral valuation metric preferred for comparing companies.", example: "Company A: EV/EBITDA = 8×. Industry average = 12×. Company A appears undervalued relative to peers.", context: "EV/EBITDA is the preferred metric in M&A and private equity because it's comparable regardless of how a company is financed (debt vs equity). Lower is cheaper — all else equal." },
  { id: "peg-ratio",          term: "PEG Ratio",               category: "Fundamental Analysis", definition: "Price-to-Earnings divided by earnings growth rate. A refinement of P/E that accounts for growth. PEG <1 suggests undervalued relative to growth; PEG >2 suggests expensive.", example: "Stock with P/E of 30× growing earnings at 30%/year has PEG = 1.0 — fair value. Same P/E at 10% growth = PEG 3.0 — expensive.", context: "Coined by Peter Lynch. PEG reveals that a 'high' P/E stock may be cheap if it's growing fast, while a 'low' P/E stock may be expensive if it's shrinking." },
  { id: "price-to-book",      term: "Price-to-Book Ratio (P/B)", category: "Fundamental Analysis", definition: "Stock price divided by book value per share (assets minus liabilities per share). Shows how much investors pay per dollar of net assets.", example: "A P/B of 1.5× means investors pay $1.50 for every $1 of net assets. A P/B below 1 might indicate undervaluation or structural problems.", context: "Warren Buffett built his early fortune buying stocks below book value. Today, intangible assets (brands, patents, software) make P/B less useful for tech companies but crucial for banks and industrials." },

  // ── Additional cross-unit terms ────────────────────────────────────────────
  { id: "asset-class",         term: "Asset Class",            category: "Foundations", definition: "A group of investments sharing similar characteristics, market behavior, and regulatory treatment. The four main classes: equities, fixed income, cash, and alternatives.", example: "Stocks, bonds, real estate, commodities, and cash are distinct asset classes that respond differently to economic conditions.", context: "Different asset classes respond differently to inflation, interest rates, and economic cycles. This is the basis for strategic asset allocation and portfolio diversification." },
  { id: "alternative-assets",  term: "Alternative Assets",     category: "Funds", definition: "Non-traditional investment categories including private equity, hedge funds, venture capital, real estate, commodities, and infrastructure.", example: "A pension fund allocates 20% to alternatives including private equity buyouts and infrastructure projects.", context: "Alternatives often have low correlation to public stocks and bonds, providing diversification benefits. They typically require longer lock-up periods and higher minimum investments." },
  { id: "commodities",         term: "Commodities",            category: "Alternative Assets", definition: "Physical goods traded on exchanges: energy (oil, natural gas), metals (gold, copper), and agricultural products (wheat, corn, soybeans).", example: "When OPEC cuts oil production, crude oil prices rise. When US corn harvest is strong, corn prices fall.", context: "Commodities are real assets that often perform well during inflation — a key portfolio diversifier. Gold historically serves as a store of value during crises and currency debasement." },
  { id: "real-estate-invest",  term: "REIT (Real Estate Investment Trust)", category: "Alternative Assets", definition: "A company that owns income-producing real estate and is required to distribute 90%+ of taxable income as dividends. Trades on exchanges like a stock.", example: "Simon Property Group is a mall REIT. Prologis owns logistics warehouses. Both trade on NYSE and pay large dividends.", context: "REITs provide real estate exposure without directly buying property. They offer high dividend yields, inflation protection, and diversification — while remaining highly liquid." },
  { id: "venture-capital",     term: "Venture Capital",        category: "Alternative Assets", definition: "Private equity investment in early-stage, high-growth companies in exchange for equity stakes. High-risk, high-reward — most investments fail, but winners can return 50–100×.", example: "Sequoia Capital invested $60M in WhatsApp. Facebook acquired it for $19B — a 300× return.", context: "Venture capital funds the innovation economy. It's only accessible to institutional investors and very high net worth individuals. Returns are highly variable and illiquid for 7–10 years." },
  { id: "private-equity",      term: "Private Equity",         category: "Alternative Assets", definition: "Investment in companies not listed on public stock exchanges. Typically involves buying controlling stakes, improving operations, and selling 5–7 years later.", example: "Blackstone buys a hotel chain for $5B, operates it more profitably for 6 years, sells for $9B — a strong private equity return.", context: "Private equity has historically outperformed public markets by 3–5% annually. But returns are illiquid, and leverage is heavily used, increasing risk during downturns." },
  { id: "long-position",       term: "Long Position",          category: "Strategy", definition: "Owning an asset with the expectation that its price will rise. The standard investment posture. Maximum loss is limited to the amount invested.", example: "Buying 100 Tesla shares expecting the price to rise over the next year is a long position.", context: "Being 'long' means you profit from price increases. Contrasted with being 'short' — which profits from price declines. Most retail investors only take long positions." },
  { id: "absolute-return",     term: "Absolute Return",        category: "Strategy", definition: "An investment strategy aiming to generate positive returns regardless of overall market direction, as opposed to relative-return strategies that simply try to beat a benchmark.", example: "A hedge fund targeting 6–8% annual gains whether markets rise or fall is employing an absolute return strategy.", context: "Absolute return strategies often use derivatives, short selling, and leverage. They appeal to investors who want stable returns uncorrelated to equities — but fees are typically very high." },
  { id: "value-investing",     term: "Value Investing",         category: "Strategy", definition: "Buying securities trading below their estimated intrinsic value — typically with low P/E, low P/B, or strong cash flows — and waiting for the market to recognize fair value.", example: "Warren Buffett bought Coca-Cola in 1988 at ~12× earnings when the market was ignoring it. It became one of his most profitable positions ever.", context: "Value investing was pioneered by Benjamin Graham and popularized by Buffett. It requires patience — cheap stocks can stay cheap for years before the market recognizes their value." },
  { id: "growth-investing",    term: "Growth Investing",        category: "Strategy", definition: "Buying companies expected to grow revenue and earnings significantly faster than the market average, often at premium valuations.", example: "Amazon traded at 100–200× earnings for years. Investors paid premium P/E because revenue was growing 25–30% annually.", context: "Growth investing outperforms in low-interest-rate environments. Higher rates hurt growth stocks most because their far-future earnings are discounted at a higher rate." },
  { id: "market-sentiment",    term: "Market Sentiment",        category: "Behavioral", definition: "The overall attitude or feeling of investors toward a particular market or asset. Ranges from extreme fear to extreme greed and often drives short-term price movements.", example: "CNN's Fear & Greed Index, put/call ratios, and VIX are common sentiment gauges. Extreme greed often precedes corrections; extreme fear often precedes rallies.", context: "Warren Buffett's famous principle: 'Be fearful when others are greedy, and greedy when others are fearful.' Sentiment extremes create the best opportunities for contrarian investors." },
  { id: "economic-indicators", term: "Economic Indicators",    category: "Macro", definition: "Statistics tracking economic health. Leading indicators predict future activity; coincident indicators measure current activity; lagging indicators confirm past trends.", example: "Leading: yield curve, building permits, stock prices. Coincident: employment, GDP. Lagging: CPI, unemployment duration.", context: "Markets react most violently to leading indicators. The Non-Farm Payrolls report (first Friday of each month) is consistently the most market-moving regular data release." },
  { id: "exchange-rate",       term: "Exchange Rate",          category: "Macro", definition: "The price of one currency in terms of another. Exchange rates constantly fluctuate based on interest rate differentials, trade flows, inflation, and market sentiment.", example: "EUR/USD = 1.08 means 1 Euro buys 1.08 US Dollars. A stronger dollar buys more foreign currency.", context: "Exchange rates significantly affect international investments. A strong dollar reduces the value of foreign assets for US investors. Currency risk is the hidden risk of global portfolios." },
  { id: "bollinger-bands",     term: "Bollinger Bands",        category: "Technical Analysis", definition: "A technical indicator with a moving average and upper/lower bands set 2 standard deviations away, measuring volatility and identifying potential price extremes.", example: "When a stock's price touches the upper Bollinger Band, it may be overbought. When it touches the lower band, oversold.", context: "Created by John Bollinger in the 1980s. Band 'squeeze' (narrow bands) signals low volatility and typically precedes a significant price breakout in either direction." },
  { id: "candlestick",         term: "Candlestick Chart",      category: "Technical Analysis", definition: "A chart type showing four price points per period: open, high, low, close. Green/white candles = price rose; red/black candles = price fell.", example: "A 'bullish engulfing' pattern (large green candle fully engulfs prior red candle) after a downtrend often signals a reversal.", context: "Developed in 18th-century Japan for rice trading. Now the universal standard for financial price charts worldwide. Dozens of named candlestick patterns exist with varying reliability." },
  { id: "risk-free-rate",      term: "Risk-Free Rate",         category: "Risk", definition: "The theoretical return on a zero-risk investment. In practice, the yield on short-term US Treasury Bills is used as the proxy for the risk-free rate.", example: "If 3-month T-bills yield 5.25%, any investment must beat 5.25% to justify taking any risk at all.", context: "The risk-free rate is the starting point for all asset pricing models. Every investment is evaluated as: risk-free rate + premium for taking risk. Higher risk-free rates raise the bar for stocks." },
  { id: "ebitda",              term: "EBITDA",                 category: "Fundamental Analysis", definition: "Earnings Before Interest, Taxes, Depreciation, and Amortization. A proxy for operating cash flow used to compare companies across different capital structures and tax situations.", example: "Company A: $500M revenue, $200M EBITDA = 40% EBITDA margin. In M&A, might be valued at 10× EBITDA = $2B enterprise value.", context: "EBITDA is the primary M&A and private equity valuation metric. Critics note it ignores real costs like capex and interest — Charlie Munger called it 'earnings before bad stuff.'" },
  { id: "hedge-fund",          term: "Hedge Fund",             category: "Alternative Assets", definition: "A private investment fund using sophisticated strategies unavailable to mutual funds — including short selling, leverage, derivatives, and arbitrage — available only to accredited investors.", example: "Bridgewater Associates, Citadel, and Renaissance Technologies manage hundreds of billions and use quantitative or macro strategies.", context: "Hedge funds charge '2 and 20': 2% annual management fee + 20% of profits. Most fail to justify these fees versus simple index funds over time." },
  { id: "sharpe-ratio-r",      term: "Sortino Ratio",          category: "Risk", definition: "A variation of the Sharpe Ratio that only penalizes downside volatility (harmful risk) rather than total volatility. A more precise risk-adjusted return measure for asymmetric strategies.", example: "A fund with 15% returns, 10% total volatility, and 6% downside volatility vs 4% risk-free rate: Sortino = (15−4)/6 = 1.83.", context: "The Sortino Ratio is preferred for strategies that aim to limit losses (asymmetric return profiles). Upside volatility isn't bad — only downside volatility represents true investor risk." },
];

export const GLOSSARY_CATEGORIES = [...new Set(GLOSSARY_TERMS.map(t => t.category))].sort();

export function getTermById(id) {
  return GLOSSARY_TERMS.find(t => t.id === id);
}

export function getTermsByCategory(category) {
  return GLOSSARY_TERMS.filter(t => t.category === category);
}

export function searchTerms(query) {
  const q = query.toLowerCase();
  return GLOSSARY_TERMS.filter(t =>
    t.term.toLowerCase().includes(q) ||
    t.definition.toLowerCase().includes(q) ||
    t.category.toLowerCase().includes(q)
  );
}
